### ISSUE TITLE
TypeError: this.adapter.init is not a function

### ISSUE THREAD

**Issue by Umut-Ozkan** [barbarbar338/bookman#2]
![image](https://user-images.githubusercontent.com/68606364/113168106-050ff100-924d-11eb-89c3-c7eb312caa10.png)
  
  
İnfo
Node Version: 14.x
i use glitch

**Comment by Umut-Ozkan** [comment]
knkam zaten başlar başlamaz hata veriyor

**Comment by barbarbar338** [comment]
> Can I see the code you use

**Comment by barbarbar338** [comment]
you have to specify an adapter. Here is an example to use fs adapter
```js
const { Database, adapters } = require("bookman");
const db = new Database(new adapters.FS({
    defaultDir: "bookman",
    databaseName: "gif",
}));
```
